config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists
  resources :tasks do 
    patch :mark_completed, on: :member
  end

  root to: 'lists#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks, dependent: :destroy
    belongs_to :user 
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @new_task = Task.new
    @tasks = @list.tasks
  end

  # GET /lists/new
  def new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def create
        @task = Task.create(task_params)
        if @task.save
            redirect_to list_path(@task.list_id)
        else 
            redirect_to root_path
        end   
    end
    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        if @task.update(task_params)
            redirect_to list_path(@task.list_id)
        else 
            redirect_to root_path
        end 
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to root_path
    end

    def mark_completed
        @task = Task.find(params[:id]) 
        @task.update_column(:complete, !@task.complete)
        redirect_to list_path(@task.list_id)
    end

    private
    def task_params
        params.require(:task).permit(:title, :complete, :list_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in?%>
    <%= link_to "exit", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to new_user_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <% if list.user == current_user %>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>
<table>
<% @tasks.each do |task| %>
<tr>
      <td><%= form_with url: mark_completed_task_path(task), method: :patch do |f| %>
        <%= f.check_box :complete, :checked => task.complete, onclick: 'this.closest("form").submit()' %>
      <% end %></td>

      <% if task.complete == true %>
        <td><p><strike><%= task.title%></strike></p></td>
      <% else %>
        <td><p><%= task.title%></p></td>
      <% end %>

  <td><%= link_to 'Edit', edit_task_path(task) %></td>
  <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  
<% end %>
</tr>
</table>

<table>
  <tr>
    <%= form_for @new_task do |f| %>
      <td><p><%= f.text_field :title %></p></td>
      <%= f.hidden_field :list_id, :value => @list.id %>
      <td><%= f.submit "add Todo" %></td>
    <% end %>
  </tr>
</table>
<%= link_to 'Back', lists_path %>

app/views/tasks/edit.html.erb
<h2>змінити</h2>
<%= form_for :task, url: task_path(@task), method: :patch do |f| %>
<% if @task.errors.any? %>
<% @task.errors. full_messages.each do |msg| %>
<div class="alers alers-danger"><%= msg %></div>
<% end %>
<% end %>
	<p>
		назва <br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>
		<%= f.submit ({:class => 'btn btn-success'})%>
	</p>
	<% end %>
    <%= link_to 'Back', lists_path %>